import './globals.css'
import { Inter } from 'next/font/google'
import { Footer, Navbar } from '@/components'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Phim mới',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='absolute z-50'>
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  )
}
